### ISSUE TITLE
Wrong Last backup date

### ISSUE THREAD

**Issue by Tyerial12** [Nexus-Mods/NMM-Test-Builds#59] opened 2016-05-04 21:15 UTC
I just backed up on 5/4/2016 and it says last backed up 4/29/2016. No matter what day i Back up it never changes

latest build aswell

**Comment by crowbar01** [comment] 2016-05-04 21:17
Seconded, I'm getting 28/4/2016, backed up 5/5/2016, build 0.62.8 - Also never changes here....when it gets passed "invalid key"

**Comment by roamwild** [comment] 2016-05-05 01:37
https://nexusmodmanager.slack.com/archives/bug_user_discussion/p1462308921000585
'Last Backed Up'  profile column in NMM <BackupDate> doesn't update:
From the label 'Last Backed Up' it seems to me as if this should reflect the date of the last profile Update through NMM ("Updated: mm/dd/yyyy" on its Web page). Currently seems fixed at the creation/first upload date for any given <onlineId>. Maybe this just isn't finished/implemented yet or I don't understand the intent, so I'm not creating an Issue, I'm mostly curious whether this is finished or is working as intended. Couldn't find any prior discussion about this field/feature, please refer me if I missed some (edited)

**Comment by DuskDweller** [comment] 2016-05-05 15:22
Should be fixed in the next release!

**Closed as completed** 2016-05-05 15:51 UTC
Labels: bug
