### ISSUE TITLE
NMM 0.62.2 - NMM putting extracted mods into numerically named folders in Virtual Install

### ISSUE THREAD

**Issue by KunoMochi** [Nexus-Mods/NMM-Test-Builds#20] opened 2016-04-26 00:35 UTC
NMM extracted some mods into the Virtual Install folder normally with mod named folders, then it started extracting them into numerically named folders. Possibly some sort of memory address offset going on with the naming?

![nmm0-62-2_virtualinstall_foldernames](https://cloud.githubusercontent.com/assets/7691651/14803151/1f4a83b4-0b25-11e6-8419-4cb04c3c8124.png)
![nmm0-62-2_virtualinstall_foldernames2](https://cloud.githubusercontent.com/assets/7691651/14803152/22a1a98e-0b25-11e6-909f-33b477441647.png)

**Comment by crowbar01** [comment] 2016-04-26 00:39
Can verify, also getting the same folder extractions

**Comment by AraFox** [comment] 2016-04-26 00:40
+1 Just noticed this today, but it's been doing it all along.

**Comment by KunoMochi** [comment] 2016-04-26 00:49
I cannot uninstall a mod individually with a folder like this. When I try, NMM ends up hanging on even the smallest mod. I can, however, use the "Uninstall all active mods" feature to uninstall the mods just fine.

Uninstalling a mod with a properly named folder then reinstalling it resulted in the mod getting a numerical folder as well.

Reinstalling NMM (and clearing all config files) also doesn't seem to fix the issue. It continues to do this with the first mod I installed.

**Comment by crowbar01** [comment] 2016-04-26 01:21
Can also verify mod re-installations are now getting numerical installation folders, instead of named as they had previously

**Comment by DuskDweller** [comment] 2016-04-28 17:34
This is working as intended, we switched from using the mod file name to the downloadID (if available).
This shouldn't cause any issue, are you still having this uninstall bug Kuno?

**Comment by KunoMochi** [comment] 2016-04-28 20:04
Ahh okay, a little bit of confusion but if that's the case then it sounds like the numerical folders are working as intended.

There are a few folders that do not do so, though, as you can see in the screenshot. They might be just mods that have been manually added into NMM. Not sure why that one mod is in a "-1" folder, though... I'll have to see if that mod still does that later.

As for the uninstalling bug, it hasn't happened yet on 0.62.3 nor on 0.62.5. I'll let you know if it happens again but for the time being, it is a bit early to say that it is confirmed to be gone.

**Comment by DuskDweller** [comment] 2016-04-29 09:42
Thanks, that "-1" is a bug, it should use the mod filename when the downloadid is invalid.

**Comment by KunoMochi** [comment] 2016-04-29 11:23
Just for reference, the mod with the "-1" folder is [**Simple Female Running Animation**](https://www.nexusmods.com/skyrim/mods/56931/?) but I had changed an internal file's name from running to sprint and left the archive name the same. That might have caused a bit of confusion for NMM.

**Comment by DuskDweller** [comment] 2016-04-29 14:41
I can confirm this is fixed in the next release.

**Closed as completed** 2016-05-04 13:01 UTC
Labels: bug
