### ISSUE TITLE
(0.62.6 | Web) Profile downloads wrong archive - Mod with multiple 'Main files' on Nexus File Page 

### ISSUE THREAD

**Issue by roamwild** [Nexus-Mods/NMM-Test-Builds#49] opened 2016-04-30 02:43 UTC
Profile contains mod with multiple Main Files, 
These archives have  different filenames but identical directories and filenames inside.
NMM downloads the first of these archives and extracts the .nifs to their VirtualInstall directory
NMM does not automatically activate these (wrong) files because cache/archive info is different?

Download Manley's profile 'Post update basic (v.2)' http://www.nexusmods.com/fallout4/profiles/2155/
- mod Larger Hunting Rifle Silencer on that profile page shows 1.375x version
  NMM downloads the other, first 'Main File' 1.25x http://www.nexusmods.com/fallout4/mods/7457/?

![wrong main file](https://cloud.githubusercontent.com/assets/18669746/14933384/c10c2ca6-0e5a-11e6-844c-ee2b57433483.jpg)
I just went ahead and arbitrarily activated this 1.25x file for this profile, it wrote properly to virtualmodconfig.xml. I don't intend to actually use this profile, was just testing it out.

**Comment by DuskDweller** [comment] 2016-05-11 18:03
We're looking into this issue.

**Comment by DuskDweller** [comment] 2016-05-13 15:03
Can you try updating your profile using 0.62.10 ? It looks like the the info in the profile are incorrect (caused by some nmm-server file identification issues).

**Comment by roamwild** [comment] 2016-05-15 01:02
This is @manley_steele 's profile used in my original post so I can't update it. I at least created a new profile which can properly download/find this mod: http://www.nexusmods.com/games/profiles/3690
1. http://www.nexusmods.com/fallout4/mods/7457/ Download with Manager (1.375x) version 
2. Activate this mod and save profile, backed up from main toolbar (partial failure) https://github.com/Nexus-Mods/NMM-Test-Builds/issues/31
3. Delete (1.375x) mod with NMM, YES to uninstall and delete permanently
4. Restore this profile through NMM creating (Backed1) which shows 1 active mod
5. Activate (Backed1) but do not get a prompt to download missing files. Local profile now shows (0) Active Mods
6. Restore (Backed2) version through NMM
7. Re-start NMM, Activate (Backed2) and get prompt to download missing files (no Details available)
8. Click YES, (1.375x) file is downloaded and installed and activated.

**Comment by Manley-Steele** [comment] 2016-05-15 02:05
```
Loading: More Durable Power Armor - 75%.esp (I:\SteamLibrary\steamapps\common\Fallout 4\Data\More Durable Power Armor - 75%.esp) (False)
Loading: keyNuker.esp (I:\SteamLibrary\steamapps\common\Fallout 4\Data\keyNuker.esp) (False)
```

Setting up listener on Nexus Mod Manager-Fallout4IpcServer/Fallout4Listener at 2016-05-14 20:51:09
Running Application.
ModUpdateCheck FAILED: Cannot reach the Nexus metadata server.

Tracing an Unhandled Exception:
Exception: 
Message: 
    An item with the same key has already been added.
Full Trace: 
    System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Nexus.Client.ModManagement.ModUpdateCheckTask.CheckForModListUpdate(List`1 p_lstModList)
   at Nexus.Client.ModManagement.ModUpdateCheckTask.DoWork(Object[] p_objArgs)
   at Nexus.Client.ThreadedBackgroundTask.RunThreadedWork(Object p_objArgs)
   at Nexus.Client.Util.Threading.TrackedThread.RunParameterizedThread(Object p_objParam)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)

That is the end of my last tracelog.
 It was made after I downloaded 3.75x and got the wrong ID for it.

[I:\Games\Nexus Mod Manager\Fallout4\Mods\downloads\Larger Hunting Rifle Silencer (1.375x)-7457-1-0.7z] Adding mod from archive.
ModUpdateCheck FAILED: Cannot reach the Nexus metadata server.
ModUpdateCheck FAILED: Cannot reach the Nexus metadata server.

Tracing an Unhandled Exception:
Exception: 
Message: 
    An item with the same key has already been added.
Full Trace: 
    System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Nexus.Client.ModManagement.ModUpdateCheckTask.CheckForModListUpdate(List`1 p_lstModList)
   at Nexus.Client.ModManagement.ModUpdateCheckTask.DoWork(Object[] p_objArgs)
   at Nexus.Client.ThreadedBackgroundTask.RunThreadedWork(Object p_objArgs)
   at Nexus.Client.Util.Threading.TrackedThread.RunParameterizedThread(Object p_objParam)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)

Tracing an Unhandled Exception:
Exception: 
Message: 
    Object reference not set to an instance of an object.
Full Trace: 
    System.NullReferenceException: Object reference not set to an instance of an object.
   at Nexus.Client.ModManagement.UI.ProfileManagerControl.ViewModel_CheckingMissingDownloadID(Object sender, EventArgs`1 e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at Nexus.Client.ModManagement.UI.ProfileManagerControl.tsbShare_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

This is the end of the trace log from trying to update the profile.

NMM closed with error for both tracelogs.

I'm going to try to update file ID again.

**Comment by Manley-Steele** [comment] 2016-05-15 02:21
My NMM still thinks that Larger Hunting Rifle Silencer 3.75x has Download ID 26290.

**Comment by DuskDweller** [comment] 2016-05-18 16:52
All these issues should have been fixed with recent client and server side fixes, if you're still experiencing any of these using newly created profiles please open a new issue.

**Closed as completed by DuskDweller** 2016-05-18 16:52 UTC
Labels: bug
