### ISSUE TITLE
NMM 0.62.19 - NMM still creates a new profile when restoring from backup file

### ISSUE THREAD

**Issue by KunoMochi** [Nexus-Mods/NMM-Test-Builds#119] opened 2016-06-23 17:50 UTC
### Issue:

When restoring form a backup file, NMM is still creating a new profile for it.

As a side effect, it also keeps the profile you were on as empty when you do "Purge and Restore". In this case, "_0.62.19 Test Profile 2_" was the profile I was on when I was restoring from the backup file. (See image below)
### Steps to reproduce:
1. Create a backup file (Tools > "Restore and Backup" > "Create Mod Installation Backup.")
2. Go to Tools > "Restore and Backup" > "Restore Mod Installation Backup"
3. Select the created backup file
4. Click on "Purge and Restore"
5. After restoring is complete, check the Profiles drop down

I haven't tested "Restore" yet but I'm guessing it will work the same way during the restoring process.
### Images:

![nmm0-62-19_restoredbackupprofile](https://cloud.githubusercontent.com/assets/7691651/16313900/520d1daa-3949-11e6-9ded-be7caaa3507d.png)

**Comment by DuskDweller** [comment] 2016-06-27 11:43
Thanks for the report!
The issue with the blanked current profile is fixed in the next release.
The backup profile added to the list is working as intended, having a generic name was an issue and it's also fixed in the next release.

**Closed as completed by DuskDweller** 2016-06-27 11:43 UTC
Labels: bug
