### ISSUE TITLE
NMM 0.62.6 - Deleting mod causing NMM to hang, crashes when NMM is reinstalled

### ISSUE THREAD

**Issue by KunoMochi** [Nexus-Mods/NMM-Test-Builds#56] opened 2016-05-02 20:47 UTC
**Issue:**
Deleting a mod was causing NMM to hang. Task Manager showed NMM taking up the rest of my system's RAM (6-7GB) for a mod with a file size of 11KB.

Does not seem to be affecting other users.

_Idle RAM usage:_
![nmm_idlememoryusage1](https://cloud.githubusercontent.com/assets/7691651/14967205/32d94f0a-1084-11e6-9133-68e73cfa2287.png)
![nmm_idlememoryusage2](https://cloud.githubusercontent.com/assets/7691651/14967210/34ba7f74-1084-11e6-84d4-52cc02734f79.png)

_Mod file size and delete:_
![nmm_brawlbugsfilesize](https://cloud.githubusercontent.com/assets/7691651/14967213/383114b0-1084-11e6-8649-5e7078dc8479.png)
![nmm_deletemod](https://cloud.githubusercontent.com/assets/7691651/14967221/3dab4cb2-1084-11e6-89ce-a41effdcfc09.png)

_Uninstalling RAM usage:_
![nmm_uninstallramusage1](https://cloud.githubusercontent.com/assets/7691651/14967223/4250508c-1084-11e6-989e-85eb5da1708c.png)
![nmm_uninstallramusage2](https://cloud.githubusercontent.com/assets/7691651/14967227/43d5e2b4-1084-11e6-89ed-0e5a559cfc05.png)
![nmm_uninstallramusage3](https://cloud.githubusercontent.com/assets/7691651/14967228/454d849e-1084-11e6-9e51-6136bf5cdcad.png)

**Method tried:**
Uninstalled NMM, removed NMM and all of its content, then reinstalled NMM. Tried to delete the mod again but causes the following trace log error.

```
Tracing an Unhandled Exception:
Exception: 
Message: 
    Invalid character in the given encoding. Line 4191638, position 16.
```

[TraceLog20160502162934.txt](https://github.com/Nexus-Mods/NMM-Test-Builds/files/245869/TraceLog20160502162934.txt)

_System Info:_
**OS:** Windows 7 Ultimate 64-bit
**CPU:** AMD Phenom II X4 955
**RAM:** 8GB DDR3
**GPU:** NVIDIA GeForce 660Ti
**.NET Framework:** 4.6+
**Anti-Virus:** Microsoft Security Essentials

**Comment by roamwild** [comment] 2016-05-02 21:10
Can't replicate this in any way, in any Game Mode, with any Mods. Tried with the mod from screenshot and with random Mods - some each installed, activated, and greyed out. I have relatively few Installed Mods (100 or less for each game).

C:\Nexus Mod Manager\Nexusclient.exe 0.62.6
Windows 7 Home Premium 64-bit SP1, .NET 4.6+, Microsoft Security Essentials
Intel Core i7-3770
More detailed system info http://pastebin.com/u99wYwd1

**Comment by KunoMochi** [comment] 2016-05-03 03:35
Currently retracing my steps. It is happening on version 0.62.5 as well so I think it might be something I did that made this happen. Possibly when I moved the Virtual Install folder around to test another issue.

I'm going to try switching profiles, then try switching profiles again after I moved the Virtual Install folder out and have it recreated again.

**Comment by DuskDweller** [comment] 2016-05-03 08:34
Kuno can you open the modlist.xml file for that profile using notepad++ and check what's on line 4191638 ?

**Comment by KunoMochi** [comment] 2016-05-03 11:36
The modlist.xml for that profile only goes up to line 107525. (It seems like I can't upload XML files here so I converted it to a text file instead.)
[modlist.txt](https://github.com/Nexus-Mods/NMM-Test-Builds/files/246770/modlist.txt)

Here's another trace log I got recently when I uninstalled then reinstalled NMM again and tried to delete the mod.

```
Tracing an Unhandled Exception:
Exception: 
Message: 
    Invalid character in the given encoding. Line 7918987, position 67.
```

[TraceLog20160503072404.txt](https://github.com/Nexus-Mods/NMM-Test-Builds/files/246767/TraceLog20160503072404.txt)

**Comment by DuskDweller** [comment] 2016-05-03 12:25
Are you sure that's the correct file? I think you may have a (somehow) bloated profile file (with millions of lines) that would also explain the size in memory.

**Comment by AraFox** [comment] 2016-05-04 01:28
Well, I can confirm this issue. The same thing just happened to me on 62.7 when attempting to delete a mod. NMM devours my system's RAM and then just locks down, completely unresponsive until I close it in task manager. I can't delete the mod at this point using mod manager. I can also confirm that my modlist.xml has no line 4191638, though mine goes up to 219799. 

Initially, I didn't notice the drag on the RAM, but having come here to see if anyone else had this problem I was able to dig a little deeper and reproduce the exact same issue (attempting to delete a different mod though). 

addendum: I may have found the culprit. Though the profile I was working on was named "FoxTest_0.62.7" (not yet uploaded to nexus) and the modlist.xml was as listed above, I decided to dig through the other profiles I'd created. First of all, I'd like to point out that there appear to be folders still in the directory for profiles I have since deleted from NMM - not sure if that's intentional or not so just want to mention it. None of those folders were any different than "FoxTest_0.62.7" but the folder for the profile I named "FoxTest.62.3" had a modlist.xml that was too large to look at with Notepad++

![snip](https://cloud.githubusercontent.com/assets/18659713/15003199/0a6c4e00-116f-11e6-9eb9-ce20a378aa0f.jpg)

Which belongs to this profile:

http://www.nexusmods.com/games/profiles/2485/?tb=files&pUp=1

**Comment by DuskDweller** [comment] 2016-05-04 09:48
What's the size of that file?
Can you also check what's going on with the "VirtualModConfig.xml" file in Mods/VirtualInstall ?

**Comment by AraFox** [comment] 2016-05-04 10:40
ha. haha. Y'know just a wee lil ol' 1,030,925KB. All my other modlist.xml files are around 14 to 15,000 KB. I should have mentioned that last night. It was late, I was tired, sorry bout it.

The VirtualModConfig file is just 15,856KB.

**Comment by KunoMochi** [comment] 2016-05-04 16:07
I was thinking the same thing as @AraFox. It might be from one of the profiles that I had with a bunch of symbols in it (including Arafox's profiles).

I deleted them, uninstalled NMM and removed all content, then reinstalled NMM. On start up, no more errors popping up. Tried to delete the same mod(s) I tried to delete before and they were removed without a problem.

I'll be testing out which symbols are doing this so we can have a more comprehensive list of which ones are causing this to happen.

**Comment by DuskDweller** [comment] 2016-05-05 15:22
Thanks Sherlock :D

**Comment by KunoMochi** [comment] 2016-05-05 18:31
Separate issue referenced for list of illegal characters.
https://github.com/Nexus-Mods/NMM-Test-Builds/issues/64

**Comment by DuskDweller** [comment] 2016-06-23 09:34
This was actually fixed in one of the latest releases.

**Closed as completed by DuskDweller** 2016-06-23 09:34 UTC
Labels: bug
