### ISSUE TITLE
Profile uploads, NMM errors. 62.6

### ISSUE THREAD

**Issue by crowbar01** [Nexus-Mods/NMM-Test-Builds#47] opened 2016-04-30 01:41 UTC
While the invalid character bug appears to be annihilated, when uploading a profile WITH invalid characters, NMM will tell you Invalid Characters as an error, but the profile will still upload to the site. Small, but might be worth looking at. Though, no crash! Props to the devs

**Comment by DuskDweller** [comment] 2016-05-05 14:56
Can you post a screenshot if you're still experiencing this issue?

**Comment by KunoMochi** [comment] 2016-05-06 16:15
I can confirm this happening as well. It was touched upon in this report: https://github.com/Nexus-Mods/NMM-Test-Builds/issues/64

Still occurs as of 0.62.9.

What I suspect is that since the error message only pops up after the 4th and final step, the profile gets uploaded first before the error is thrown.

**Steps to reproduce:**
1. Create a new profile, using one or more of these characters in the name ( `\ : / " < >` )
2. Select the newly created profile and click "Backup"  or "Backup and Share"
3. Let it run through all 4 steps of uploading until an error pops up (either "Illegal characters" or "Object ref not set")
4. Close error message and refresh list of online profiles

**Comment by DuskDweller** [comment] 2016-05-11 18:02
This should be fixed with 0.62.10 !

**Closed as completed by DuskDweller** 2016-05-11 18:02 UTC
Labels: bug
