### ISSUE TITLE
update info for mod in profile

### ISSUE THREAD

**Issue by h-lucz** [Nexus-Mods/NMM-Test-Builds#28] opened 2016-04-27 12:14 UTC
EBT is displayed as not being up to date, but actually I installed latest version 3.6c. See image.
![skyrim mod profile file update info](https://cloud.githubusercontent.com/assets/18660199/14851759/5412e8a8-0c82-11e6-9a35-e144fd4812ea.jpg)

**Comment by DuskDweller** [comment] 2016-05-05 11:40
Do you still get this issue? I just checked and your profile is no longer online.

**Comment by KunoMochi** [comment] 2016-05-06 15:25
**Profile used:** http://www.nexusmods.com/games/profiles/3500/?

EBT seems to be fixed now but other mods like [The Ruffled Feather](http://www.nexusmods.com/skyrim/mods/13268/?) still does this. Also, the general Nexus Games theme blends right into the "outdated mod" background.
![nmm_profilepage_outdatedmod1](https://cloud.githubusercontent.com/assets/7691651/15077556/061735d0-137d-11e6-8738-c5311a6ddbf6.png)

**Additional Note:**
There are also mods that like to have mismatching version numbers ([40 years old Normal map by Gs_storm](http://www.nexusmods.com/skyrim/mods/34642/?) shown below). (Another example would be [newermind43's True Thief Armor](http://www.nexusmods.com/skyrim/mods/38409/?).)
![nmm_profilepage_outdatedmod2](https://cloud.githubusercontent.com/assets/7691651/15077400/3f8ad1ba-137c-11e6-81a4-df73482748f1.png)

**Comment by DuskDweller** [comment] 2016-05-11 17:55
Hi Kuno, can you check again by updating the profile using the latest version (0.62.10) ?

**Comment by KunoMochi** [comment] 2016-05-12 06:28
**0.62.10 Update:**
While the _40 years old Normal Map_ mod is not indicating that it needs an update anymore, _The Ruffled Feather_ and the _True Thief Armor - Brown retexture_ mods are still indicating a need for an update.

Ran the "Check for mod update" feature but issue persists. The _True Thief Armor - Brown retexture_ seems to be missing the DownloadID even after running "Check for mod update".
![nmm0-62-10_downloadidmissing](https://cloud.githubusercontent.com/assets/7691651/15205761/205c9e7a-17e8-11e6-8320-a9d598325724.png)

I can still manually retrieve the mod info for it, though. Doing so will also fix the file for the online profile.
![nmm0-62-10_modinfo](https://cloud.githubusercontent.com/assets/7691651/15205772/309eccb8-17e8-11e6-9e19-76d09bf58d6c.png)

**Additional Note:**
Strangely, the number of files with new versions does not match the mods listed. The mod not listed under files with new versions is most likely _The Ruffled Feather_.
![nmm0-62-10_profilepage_outdatedmod3](https://cloud.githubusercontent.com/assets/7691651/15205812/7b27a6d8-17e8-11e6-91d4-2a2624cd5507.png)

**Profile used:** http://www.nexusmods.com/games/profiles/3500/

**Comment by DuskDweller** [comment] 2016-05-12 07:29
You need to use the "Get missing/outdated download ID" first, it seems you did it cause the online profile now properly recognizes the mod file.

Let me know if you find any more issues.

**Comment by KunoMochi** [comment] 2016-05-12 18:27
I actually retrieved the mod info manually since I totally missed the "Check for missing/outdated download IDs" option.

I went back to delete the file and redownload it and used that option this time. It seems to have retrieved the download ID info just fine.

The only mod with troubles now is _The Ruffled Feather 4.2.2_.

**Additional note:**
It seems like some mods I downloaded and installed before 0.62.x does not update correctly with "Check for missing/outdated download IDs" until after I delete and re-download it.

Here's what happens when I went to download the updated version of the mod file first before deleting it. In this instance, I was updating [Lind's Vaermina Robes Revamp](http://www.nexusmods.com/skyrim/mods/72751/?) from 1.0A to 1.0.3A. Note in the mods list that the install date for the mod is dated before the download date:
![nmm0-62-10_completeddlnotonlist](https://cloud.githubusercontent.com/assets/7691651/15226138/7ba8346c-184f-11e6-8d13-7c08ae993dbb.png)

**Comment by KunoMochi** [comment] 2016-05-18 08:24
**Update:**
So I had the above happen again when I went to update a mod I got from another site. The Download Date was changed but the old version was still installed. Reinstalling it should uninstall the old version then install the new version back in but it only ends up with an error during installation.

```
SaLaHair // A problem occurred during install: 
Source array was not long enough. Check srcIndex and length, and the array's lower bounds.
The mod was not installed. // Install // 
```

![nmm0-62-13_modupdateinstallerror](https://cloud.githubusercontent.com/assets/7691651/15351825/39703216-1caf-11e6-98f2-e9d4e14b47a8.png)

**Steps to reproduce:**
1. Add and install an old version of a mod manually
2. Add the updated version of mod with the same file name
3. Reinstall mod

**Comment by KunoMochi** [comment] 2016-05-18 08:41
**Second update:**
[Enhanced Blood Textures](http://www.nexusmods.com/skyrim/mods/60/?) seemed to have reinstalled with a missing Download ID when I was switching from an empty profile to a populated one. Not sure how this one happened but I wasn't able to retrieve the Download ID automatically. This caused NMM to extract the mod to a named folder in the Virtual Install folder (see image below).

Manually retrieving the mod info worked but uploading the profile online tells me that EBT 3.6c is missing on Nexus.
Profile used: http://www.nexusmods.com/skyrim/profiles/10/

**Note:**
The EBT file name has a starting space before the name.
`" Enhanced Blood Textures 3_6c NMM -60-3-6c.7z"`

![nmm0-62-13_profilemissingmods4](https://cloud.githubusercontent.com/assets/7691651/15352326/a5aed534-1cb1-11e6-8b51-f4f49d6b5bae.png)
![nmm0-62-13_profilemissingmods1](https://cloud.githubusercontent.com/assets/7691651/15352278/7282f1b8-1cb1-11e6-9597-7a0d1e8fde66.png)
![nmm0-62-13_profilemissingmods2](https://cloud.githubusercontent.com/assets/7691651/15352286/7478b6ce-1cb1-11e6-8729-a2766d45052c.png)
![nmm0-62-13_profilemissingmods3](https://cloud.githubusercontent.com/assets/7691651/15352289/7646e3fe-1cb1-11e6-8b46-fe46e9748078.png)

**Comment by DuskDweller** [comment] 2016-05-18 16:52
All these issues should have been fixed with recent client and server side fixes, if you're still experiencing any of these using newly created profiles please open a new issue.

**Closed as completed by DuskDweller** 2016-05-18 16:52 UTC
Labels: bug
