### ISSUE TITLE
Crash after updating a mod - uninstall previous version, install new version

### ISSUE THREAD

**Issue by h-lucz** [Nexus-Mods/NMM-Test-Builds#55] opened 2016-05-01 00:41 UTC
Updating a mod (esp) – uninstall/install new version - made NMM crash. After restart, the new mod version was installed, but all plugins were deactivated. One click button reactivated all plugins.
Rearrangement of load order with LOOt did not take effect as long as NMM was active/open. Just after restart of NMM the new LO - arranged with LOOT - took effect in NMM (62.6). Just FYI.
Trace Log:
[TraceLog20160430180042.txt](https://github.com/Nexus-Mods/NMM-Test-Builds/files/243889/TraceLog20160430180042.txt)

**Comment by Dooksb4u** [comment] 2016-05-01 00:59
so when uninstalling/reinstalling :( .........
[TraceLog20160501005403.txt](https://github.com/Nexus-Mods/NMM-Test-Builds/files/243893/TraceLog20160501005403.txt)
[TraceLog20160426214207.txt](https://github.com/Nexus-Mods/NMM-Test-Builds/files/243895/TraceLog20160426214207.txt)
[TraceLog20160501014822.txt](https://github.com/Nexus-Mods/NMM-Test-Builds/files/243894/TraceLog20160501014822.txt)

fo4 btw

**Comment by KunoMochi** [comment] 2016-05-01 01:05
@h-lucz 
Error message:
`The process can not access the file "C:\Games\Nexus Mod Manager\Fallout4\Mods\ModProfiles\me4b4mst\modlist.xml" access, because it is used by another process.`

That actually happened to me a couple of times. I couldn't consistently reproduce it, though.

@Dooksb4u 
Are you running NMM as an administrator?

**Comment by Dooksb4u** [comment] 2016-05-01 02:09
It works the second try but rarely the first........ I do normally run as
administrator but honestly can't be sure

**Comment by h-lucz** [comment] 2016-05-02 19:36
On May 2nd I startet NMM first with FO 4 and switched then to Skyrim (so the other way round than few days ago). After installing a mod (esp) for Skyrim NMM crashed. After restart of NMM with Skyrim the mod has been indicated as activated in Plugins and Mods tab. After that a further installation of an esp file worked as usual (no further crash). Trace Log.
[TraceLog20160502145845.txt](https://github.com/Nexus-Mods/NMM-Test-Builds/files/245777/TraceLog20160502145845.txt)

**Comment by DuskDweller** [comment] 2016-05-05 15:20
Are you still experiencing this crashes?

**Comment by DuskDweller** [comment] 2016-05-11 18:07
Considering this fixed by 0.62.9

**Closed as completed by DuskDweller** 2016-05-11 18:07 UTC
Labels: bug
