### ISSUE TITLE
Skyrim migration still unsuccessful  - from 56.1 to 62.9

### ISSUE THREAD

**Issue by prinyo** [Nexus-Mods/NMM-Test-Builds#68] opened 2016-05-07 10:23 UTC
I have both versions of NMM installed and decided to move Skyrim to 62.9.
I did a rescan for games and added Skyrim. It started reinstalling the mods and almost immediately crashed (see error below). 
Now I have 0 active mods but 204 active plugins. Selecting Restore backup profile crashes with the same error ( Tracelog attached )

All the mods were moved to one category. 
![image](https://cloud.githubusercontent.com/assets/18665141/15091556/e57ab704-144c-11e6-9871-f054e9332ed6.png)

Each of those categories contained mods added there depending on if I'm planning to use them later or to experiment with them and so on. Now they are all in the unassigned category. Except 2 that were randomly added to the category SAM - they weren't there before and they are not supposed to be there. The categories are the same but the mods are moved.

Since the game is working (NMM crashes before been able to make any changes) and I don't feel like reinstalling 208 mods by hand at the moment I'm going to leave it like that if you have anything you want me to try/test to see if I can recover the setup. If there are no ideas I'll probably stay with 56.1 forever for pre-FO4 games.

Tracing an Unhandled Exception:
Exception: 
Message: 
    Value cannot be null.
Parameter name: bytes
Full Trace: 
    System.ArgumentNullException: Value cannot be null.
Parameter name: bytes
   at System.IO.File.WriteAllBytes(String path, Byte[] bytes)
   at Nexus.Client.ModManagement.ProfileManager.SaveProfile(IModProfile p_impModProfile, Byte[] p_bteModList, Byte[] p_bteIniList, Byte[] p_bteLoadOrder, String[] p_strOptionalFiles)
   at Nexus.Client.ModManagement.ProfileManager.BackupProfile(Byte[] p_bteModList, Byte[] p_bteIniList, Byte[] p_bteLoadOrder, String p_strGameModeId, Int32 p_intModCount, String[] p_strOptionalFiles)
   at Nexus.Client.ModManagement.ModMigrationTask.AddNewProfile(Byte[] p_bteModList, Byte[] p_bteIniList, Byte[] p_bteLoadOrder, Int32 p_intModCount, Boolean p_booBackup)
   at Nexus.Client.ModManagement.ModMigrationTask.DoWork(Object[] p_objArgs)
   at Nexus.Client.ThreadedBackgroundTask.RunThreadedWork(Object p_objArgs)
   at Nexus.Client.Util.Threading.TrackedThread.RunParameterizedThread(Object p_objParam)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)

Running Threads (1)
    3 () 
        Aborted

[TraceLog20160507121017.txt](https://github.com/Nexus-Mods/NMM-Test-Builds/files/253374/TraceLog20160507121017.txt)

**Comment by prinyo** [comment] 2016-05-07 10:43
Update.
I noticed that NMM is showing profiles I had created months ago before I moved Skyrim back to 56.1. So I uninstalled 62.9 via the Windows Control panel and clicked Yes when asked if I want to remove all the data. Yet after the clean install of 62.9 I still get the same crash and the old profiles are still shown.
I'm using the same mods and install info folder from 56.1 when setting-up 62.9. 

I can see that removing the config while uninstalling had an effect om 56.1 which asked me to scan games and setup folders.

**Comment by prinyo** [comment] 2016-05-07 11:25
New update
Opening FO4 in 62.9 now (after reassigning the same mods and install info dirs it was using before) showed a message that the mods need to be reinstalled in order for the new system to work. The same message that is shown when migrating the older games. I clicked Yes and NMM crashed with the same error as with Skyrim. After reopening NMM it gets even more confusing:

![image](https://cloud.githubusercontent.com/assets/18665141/15092922/422d0fb2-1478-11e6-9005-30a07a5935ad.png)

Switching profiles doesn't help. 

[TraceLog20160507130950.txt](https://github.com/Nexus-Mods/NMM-Test-Builds/files/253389/TraceLog20160507130950.txt)

**Comment by prinyo** [comment] 2016-05-07 15:46
Yet another update

I reinstalled NMM 0.62.9 to try to fix the problem with FO4 and what I found is that the whole profiles feature is still pretty much unusable. Before the reinstall the "main", "new profile" and "test" had more than 80 mods. After the reinstall "main" is down to 39 ....

![profiles5](https://cloud.githubusercontent.com/assets/18665141/15093033/3291fe48-147b-11e6-9892-92af1ca8c338.jpg)

Mods randomly disappearing or appearing in profiles has been a deal-breaking bug from the start of the whole profiles adventure and it seems it is still unfixed.

**Comment by prinyo** [comment] 2016-05-07 18:00
-- deleted

**Comment by KunoMochi** [comment] 2016-05-07 19:22
I noticed that you do not have any default categories left over in your screenshots.have you tried removing the Categories.xml and have it recreate the file? Not sure if it might be the cause of the errors but it is worth a try.

**Comment by prinyo** [comment] 2016-05-08 10:43
> I noticed that you do not have any default categories left over in your screenshots.have you tried removing the Categories.xml and have it recreate the file? Not sure if it might be the cause of the errors but it is worth a try.

Isn't this going to create vanilla (Nexus) categories?

**Comment by KunoMochi** [comment] 2016-05-08 17:28
After some time fooling around with the Categories, I feel that it might not be the solution to this bug. Even if the Categories.xml gets recreated, the mods themselves will still go into categories that don't exist anymore.

We'll have to test around some more and see what exactly is the cause of it, if you are willing to be the guinea pig and test it around.

**Comment by prinyo** [comment] 2016-05-08 19:57
Yes, no problem. 
There are 3 problems - one is the mods moved between categories. The second one is that I can't migrate Skyrim to 62.9 at all. And the third one is that the local profiles are losing mods.

**Comment by KunoMochi** [comment] 2016-05-09 04:56
Try re-installing NMM 0.62.9 to another location and use its own folders for Fallout 4 and Skyrim then experiment around with it.

One thing I do note is that there was a problem with updating directly from 0.56.1 to I think it was 0.61.15+ one time. It required the user to update to 0.61.14 or lower first before updating to 0.61.15+ due to some changes to NMM.

I never went back to test that out again, though. I might do that and see if it is possible. I don't mind having to reinstall all of my mods over and over again if it means getting closer to a solution.

**Comment by DuskDweller** [comment] 2016-05-18 16:57
All these issues should have been fixed with recent client and server side fixes, if you're still experiencing any of these using newly created profiles please open a new issue.

**Closed as completed by DuskDweller** 2016-05-18 16:57 UTC
Labels: bug
